name: generate outputs

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  generate_outputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: gitmarker
      run: "for i in *.kicad_pcb; do git rev-parse --short HEAD | xargs -I % sed -i 's/{GITHASH}/%/g' $i; done" # add git marker
    - uses: INTI-CMNB/KiBot@v2_k7
      with:
        # Required - kibot config file
        config: config.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output